### ISSUE TITLE
Energy Analytics (All Files)

### ISSUE THREAD

**Issue by banica** [banica/2023_NASA_Space_Apps_Hackathon_Modularity#1]
Convert Energy Analytics into Human Performance Analytics (Apps)

**Comment by GeorgAC** [comment]
[Modularity Energy.zip](https://github.com/banica/2023_NASA_Space_Apps_Hackathon_Modularity/files/12837271/Modularity.Energy.zip)

**Comment by banica** [comment]
> [Modularity Energy.zip](https://github.com/banica/2023_NASA_Space_Apps_Hackathon_Modularity/files/12837271/Modularity.Energy.zip)

@GeorgAC Please put all files to the main source code repository. Thanks

**Comment by abuzatu** [comment]
@banica We can also close this issue, no?
