### ISSUE TITLE
Simulate data for a human that is losing weight

### ISSUE THREAD

**Issue by banica** [banica/2023_NASA_Space_Apps_Hackathon_Modularity#6]
See also #8 for more references. 

1. 128 kg April 2023
2. 102 kg August 2023
3. 92 kg October 2023
4. 75 kg March 2024
5. 85 kg June 2024 (+10kg of Muscles)

**Comment by banica** [comment]
6. 128 kg - 102 kg - No Sugar at All
7. 102 kg - 92 kg - Physical Activity
8. 92 kg - 75 kg - Sleep Management, Stress Management, Water, Monitoring

**Comment by banica** [comment]
1-8 High Performance Mentors (Persons that already did what you want to achieve)
1-8 (Personal) Doctor + (Personal) Nutritionist
1-8 Daily Monitoring and Coaching with Doctor & Nutritionist
1-8 Mental/Life/Career Coaching

**Comment by banica** [comment]
https://www.gmon.eu/gstd_en (Health Monitor Software gmon.eu)

**Comment by abuzatu** [comment]
@banica I used the following assumptions and then interpolated between them linearly, and then added a 0.2% noise.

Real measurement in Aug 23
```
HEALTH_PARAMETER_READING_EXAMPLE_1 = {
    "Weight": 101.9,
    "BodyFat": 25.6,
    "VisceralFat": 10,
    "BMI": 28.5,
    "MuscularMass": 72.1,
    "HydroMass": 55.2,
    "AngularPhase": 5.3,
    "Impedance": 361.0,
    "MetabolicalAge": 50,
    "BMR": 2252.9,
}
```

Start on 2022-11-01.
```
HEALTH_PARAMETER_READING_EXAMPLE_2 = {
    "Weight": 128.0,
    "BodyFat": 40.5,
    "VisceralFat": 16,
    "BMI": 35.8,
    "MuscularMass": 72.1,
    "HydroMass": 54.2,
    "AngularPhase": 5.3,
    "Impedance": 481.0,
    "MetabolicalAge": 62,
    "BMR": 2450.9,
}
```

Guess of end of year after end of fat reduction
```
HEALTH_PARAMETER_READING_EXAMPLE_3 = {
    "Weight": 83,
    "BodyFat": 8,
    "VisceralFat": 6,
    "BMI": 23.0,
    "MuscularMass": 72.1,
    "HydroMass": 55.2,
    "AngularPhase": 4.9,
    "Impedance": 280.0,
    "MetabolicalAge": 30,
    "BMR": 2034.9,
}
```

Guess for end of June after musles added
```
HEALTH_PARAMETER_READING_EXAMPLE_4 = {
    "Weight": 90,
    "BodyFat": 7.5,
    "VisceralFat": 5,
    "BMI": 25.2,
    "MuscularMass": 79.1,
    "HydroMass": 56.7,
    "AngularPhase": 6.2,
    "Impedance": 256.0,
    "MetabolicalAge": 29,
    "BMR": 2087.9,
}
```

**Comment by banica** [comment]
HEALTH_PARAMETER_READING_EXAMPLE_5 = {
    "Weight": 75,
    "BodyFat": 4.5,
    "VisceralFat": 4,
    "BMI": 22.4,
    "MuscularMass": 75.0,
    "HydroMass": 55.9,
    "AngularPhase": 5.7,
    "Impedance": 255.0,
    "MetabolicalAge": 28,
    "BMR": 2002.1,

**Comment by banica** [comment]
> HEALTH_PARAMETER_READING_EXAMPLE_5 = { "Weight": 75, "BodyFat": 4.5, "VisceralFat": 4, "BMI": 22.4, "MuscularMass": 75.0, "HydroMass": 55.9, "AngularPhase": 5.7, "Impedance": 255.0, "MetabolicalAge": 28, "BMR": 2002.1,

This is the target.
Phase 1: Get off the fat
Phase 2: Add 10+ kg of muscles
Metabolic Age: <28 years 
Actual Age: > 38+ years

**Comment by abuzatu** [comment]
@banica Is HEALTH_PARAMETER_READING_EXAMPLE_5 the target at the end of phase 1, or at end of phase 2? It seems it is end of phase 1) as at phase 2 you sad 85 the weight. What date for the end of phase 1?

**Comment by abuzatu** [comment]
@banica @GeorgAC To visualize the visualisation curves already, before they are in PowerBI, I added them in a streamlit app. That way you can check if the simulations looks reasonable to what you want.

http://194.99.21.224:8504

**Comment by abuzatu** [comment]
@banica @GeorgAC I updated the simulation to v3 with Marian's data above.

https://github.com/banica/2023_NASA_Space_Apps_Hackathon_Modularity/blob/main/data/simulations/df_simulation_human_03_plan.csv

**Comment by banica** [comment]
> @banica @GeorgAC To visualize the visualisation curves already, before they are in PowerBI, I added them in a streamlit app. That way you can check if the simulations looks reasonable to what you want.
> 
> http://194.99.21.224:8504

@abuzatu Please update the description to fit our new focus. It's not anymore Energy but Human Performance. 

![image](https://github.com/banica/2023_NASA_Space_Apps_Hackathon_Modularity/assets/350429/359c0c07-d0d3-44e7-968d-c1a35ad6dc7f)

**Comment by abuzatu** [comment]
@banica Good catch, fixed!

**Comment by abuzatu** [comment]
@banica We can close this?
