### ISSUE TITLE
[Dummy Data] Dummy Data for (Healthy) Human

### ISSUE THREAD

**Issue by banica** [banica/2023_NASA_Space_Apps_Hackathon_Modularity#8]
@abuzatu please ask me here what you need to know about my past (health) data and i will update here.

Thanks

**Comment by abuzatu** [comment]
@banica @GeorgAC I did the simulation before with the dummy values using the current measurements from Marian https://github.com/banica/2023_NASA_Space_Apps_Hackathon_Modularity/blob/main/data/simulations/df_simulation_human_01_dummy.csv 

and now added the new simulation assuming a decrease of the weight until end of year and then increase the weight only via muscle.

https://github.com/banica/2023_NASA_Space_Apps_Hackathon_Modularity/blob/main/data/simulations/df_simulation_human_02_plan.csv

**Comment by abuzatu** [comment]
@banica This should be combined with issue #6

**Comment by banica** [comment]
@abuzatu i will close this issue and keep just #6
